### ISSUE TITLE
关于模型迁移

### ISSUE THREAD

**Issue by Jiangzl** [Jerryzhangzhao/django_tfserving_web#1]
你好，我使用了你的代码，并且根据你的博客流程走了一遍，最后可以成功实现了，只是最后的预测不能正常显示出来，imagenet_id_to _name.py文件也是直接使用的你的，不知道是什么原因
file:///home/jzl/Pictures/Screenshot%20from%202019-01-22%2012-23-55.png
同时我还想请问一下，是否可以将训练好的tensorflow模型使用你的这种方法迁移到本地服务器呢？
非常感情你提供的代码和使用流程，如果你有时间，希望得到你的帮助～ 谢谢！

**Comment by Jiangzl** [comment]
你好，不好意思，不知道为什么图片没有上传成功，具体错误就是在预测结果的地方显示出现错误：
predict result: something wrong happend

**Comment by Jerryzhangzhao** [comment]
1.出现这个错误原因可能是tfserving跑得问题，也可能是图片下载过程中出现错误。可以先用我博客里的python代码测试一下图片下载过程中是否正常，再看看tfserving是否运行正常，能否正常返回结果。
2.模型迁移到本地服务器理论上是没有问题的，只要保证模型的格式是tfserving可以加载的格式即可。
